language: php

php:
    - 8.0
    - 7.4
    - 7.3


matrix:
    fast_finish: true
    include:
        - php: 7.4
          env: SYMFONY_VERSION=4.4.*
        - php: 7.4
          env: SYMFONY_VERSION=5.2.*
        - php: 7.3
          env: SYMFONY_VERSION=5.2.*
        - php: 8.0
          env: SYMFONY_VERSION=5.2.*

before_install:
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo "xdebug.mode=coverage" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/framework-bundle:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
    - vendor/bin/atoum
