services:
    Novaway\Bundle\FeatureFlagBundle\Manager\FeatureManager: '@Novaway\Bundle\FeatureFlagBundle\Manager\DefaultFeatureManager'
    Novaway\Bundle\FeatureFlagBundle\Manager\DefaultFeatureManager:
        arguments: ['@Novaway\Bundle\FeatureFlagBundle\Storage\ArrayStorage']

    novaway_feature_flag.manager:
        alias: 'Novaway\Bundle\FeatureFlagBundle\Manager\DefaultFeatureManager'

    Novaway\Bundle\FeatureFlagBundle\Storage\ArrayStorage:
        arguments:
            - "%novaway_feature_flag.features%"
    novaway_feature_flag.storage.default:
        alias: 'Novaway\Bundle\FeatureFlagBundle\Storage\ArrayStorage'

    novaway_feature_flag.listener.controller:
        class: Novaway\Bundle\FeatureFlagBundle\EventListener\ControllerListener
        arguments:
            - "@annotation_reader"
        tags:
            - { name: kernel.event_subscriber }

    novaway_feature_flag.listener.feature:
        class: Novaway\Bundle\FeatureFlagBundle\EventListener\FeatureListener
        arguments:
            - "@novaway_feature_flag.manager"
        tags:
            - { name: kernel.event_subscriber }
